library(dplyr)
print("Importing in-built dataset")
input<-mtcars[1:5,1:11]
print(input)
print("Filter function")
filter(input,am==0)
print("Select function")
select(input,wt)
print("Arrange function")
arrange(input,hp,descending=TRUE)
print("Mutate function")
mutate(input,ddisp=disp*2)
print("Rename function")
rename(input,weight=wt)
print("Summary of dataset")
summary(input)
print("Summarizing dataset")
summarize(input,mean(cyl))
print("Distinct function")
d<-distinct(input,gear)
print(d)
print("Histogram")
hist(input$mpg,col="blue",main="Histogram representing mileage ")
